### ISSUE TITLE
echarts图表上的字体有什么好的方案去适配呢

### ISSUE THREAD

**Issue by sxs1995** [njleonzhang/flexible-pc-full-screen#1]
博客很棒, echarts图表上的字体好像没有适配   您有什么好的方案吗

**Comment by njleonzhang** [comment]
echarts 图中的字体是 echarts 配置项通过 js 控制的，我没有深入去研究，但是感觉也可以通过类似计算的方式来适配。你可以考虑下啊。
配合项: https://echarts.baidu.com/option.html#title.textStyle.fontSize

**Comment by WangWeiZhang** [comment]
你好，针对这个项目，个人有些小的疑问，方便加我微信探讨一下吗，谢谢。18601240505

**Comment by njleonzhang** [comment]
@sxs1995 可以尝试下面这样的方法来转换需要写在 js 里的 px 值。（192 要改成你的 rem基数）

```
export function convertPx(px) {
  return (px / 192) * parseFloat(document.documentElement.style.fontSize.replace('px', ''))
}
```

**Comment by bf109f** [comment]
大佬请问一下 rem基数这个值是如何确定的？任意一个值都行吗？原谅我没看懂你写的那个计算方法

**Comment by njleonzhang** [comment]
@bf109f 基数就是这个插件 https://github.com/QuellingBlade/postcss-px-to-rem  的 widthOfDesignLayout 这个配置项除于 10。一看就是没认真看 blog，haha
