### ISSUE TITLE
关于项目的疑问

### ISSUE THREAD

**Issue by WangWeiZhang** [njleonzhang/flexible-pc-full-screen#2]
你好，关于项目产生几点疑问。能否加我微信18601240505或者联系我邮箱352875258@qq.com 探讨一下？ 忘回复，谢谢。

**Comment by njleonzhang** [comment]
@WangWeiZhang 就在 issue 里说吧。:)

**Comment by WangWeiZhang** [comment]
以下#号代表问题

1、我使用的是vue-cli搭建的基本项目，看见这个项目中 px自动转换成rem
#请问这个@njleonzhang/postcss-px-to-rem包和官方的postcss-pxtorem有什么区别，是一模一样的吗？还是楼主配置了什么？

2、我看见index.html里有这样一个方法来设置页面的16：9比例->
dashboardFlexible.init(16 / 9);看见使用的npm包是lib-flexible-for-dashboard
#本人先没使用postcss-pxtorem。使用的自己写的脚本，动态控制html的font-size的。
#个人下载后，在index.html引入，后调用dashboardFlexble.init(16/9）不生效

3、关于项目中的设计模式
#index.vue是跟组件，父亲组件。所有的子组件都写有echarts的配置项。但是所有的子组件的echarts图表并没看见在哪setOption()设置。

4、最重要一个问题，
#请问楼主，我如果使用vue-cli配合postcss-pxtorem + lib-flexible-for-dashboard 能否实现楼主https://github.com/njleonzhang/flexible-pc-full-screen 地址上的等比缩放效果。

**Comment by njleonzhang** [comment]
你是不是没有看博客啊，你看一下吧。从分析到使用都介绍了，你看一下就没有这些疑问了。

https://www.njleonzhang.com/2018/08/15/flexible-pc-full-screen.html

前面的问题我就不答了，请自己去看。

问题3，我用了 vue-echarts 组件:
https://github.com/njleonzhang/flexible-pc-full-screen/blob/19c6ca801cb292030247c58ccee7d4feab9481e0/src/main.js#L4

最后一个问题，当然是可以的啊。源码不是在这个项目里么。
https://github.com/njleonzhang/flexible-pc-full-screen
